---
- hosts: db1
  tasks:
    - name: create user {{ item.uname }}
      user:
        name: "{{ item.uname }}"
        group: "{{ item.group }}"
        password: "{{ item.passwd | password_hash('sha512') }}"
      with_items:
        - 
          uname: nb
          group: bin
          passwd: "123456"
        - 
          uname: wk
          group: man
          passwd: banana
        - 
          uname: dd
          group: daemon
          passwd: book
        - 
          uname: jj
          group: mysql
          passwd: 123qqq...A
        - 
          uname: xx
          group: root
          passwd: a
