---
- hosts: web
  tasks:
    - name: modify httpd.conf
      copy:
        src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        owner: root
        group: root
        mode: 0644
      tags: update_conf
      notify: reload httpd
    - name: modify index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: 0644
      tags: update_index
  handlers:
    - name: reload httpd
      service:
        name: httpd
        state: restarted

